#include <Arduino.h>
#include "model.h"  // generated by emlearn: defines darml_model_predict(int16_t*, int)

#define INFERENCE_INTERVAL_MS {{INFERENCE_INTERVAL_MS}}
#define INPUT_SIZE            {{INPUT_SIZE}}

static int16_t input_buf[INPUT_SIZE];

void setup() {
    Serial.begin(9600);
    Serial.println(F("[Darml] AVR ready."));
}

void loop() {
    // emlearn models take int16_t features. Scale your sensor readings to fit.
    for (int i = 0; i < INPUT_SIZE; ++i) {
        input_buf[i] = (int16_t)analogRead(A0);  // placeholder: wire real sensors in
    }
    int32_t pred = darml_model_predict(input_buf, INPUT_SIZE);
    Serial.print(F("[Darml] pred="));
    Serial.println((long)pred);
    delay(INFERENCE_INTERVAL_MS);
}
