[env:avr-mega328]
platform = atmelavr
board = ATmega328P
board_build.f_cpu = 16000000L
framework = arduino
monitor_speed = 9600

[env:avr-mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600
